// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkvfcjtbuajhlfkrtjnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrdmZjanRidWFqaGxma3J0am5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDI5MTEsImV4cCI6MjA2OTYxODkxMX0.yjupjKqVtxiE6oYS2xf8CxcVK62a_I_t-x1aLbmn7AE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});